services:
    fishy:
        build: .
        restart: always
        env_file: .env
        environment:
            SQLALCHEMY_DATABASE_URL: "mariadb+pymysql://root:password@127.0.0.1:3307/fishy"
        network_mode: host
        volumes:
            - /var/lib/fishy:/var/lib/fishy
        depends_on:
            db:
                condition: service_healthy
                required: true
    marznode:
        image: dawsh/marznode:latest
        restart: always
        network_mode: host
        environment:
            DEBUG: "True"
            SERVICE_ADDRESS: "127.0.0.1"
            XRAY_VLESS_REALITY_FLOW: ""
            AUTH_GENERATION_ALGORITHM: "plain"
            INSECURE: "True"
            XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
            XRAY_ASSETS_PATH: "/usr/local/lib/xray"
            XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
        volumes:
            - /var/lib/marznode:/var/lib/marznode
    db:
        image: mariadb:latest
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_DATABASE: fishy
        volumes:
            - /var/lib/fishy/mysql:/var/lib/mysql
        ports:
            - "127.0.0.1:3307:3306"
        healthcheck:
            test: healthcheck.sh --connect
            interval: 5s
            retries: 4
